---
prerun: false
dependency:
  name: galaxy
  options:
    role-file: roles/requirements.yml
    requirements-file: collections/requirements.yml
driver:
  name: docker
lint: |
  set -e
  export ANSIBLE_ROLES_PATH=${MOLECULE_EPHEMERAL_DIRECTORY}/roles
  export ANSIBLE_COLLECTIONS_PATH=${MOLECULE_EPHEMERAL_DIRECTORY}/collections
  ansible-lint --exclude ${MOLECULE_EPHEMERAL_DIRECTORY} -c .ansible-lint.yml
  flake8
platforms:
  - name: devops-dev-1
    image: geerlingguy/docker-ubuntu2404-ansible
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    command: /lib/systemd/systemd
provisioner:
  name: ansible
  env:
    ANSIBLE_CONFIG: ../../ansible.cfg
  inventory:
    links:
      hosts: ../../hosts/hosts_dev
      group_vars: ../../group_vars/
  playbooks:
    converge: ../../playbook_install.yml
scenario:
  name: default
verifier:
  name: testinfra
  options:
    sudo: true

